<a href="https://colab.research.google.com/github/sivamanikandan45/DepressionDetectionusingTransformer/blob/main/DepressionDetectionusingRoBERTa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [ ]:
import io
import pandas as pd

In [ ]:
df_train = pd.read_csv('train.csv')
print(df_train)

                                                   text  category
0     Waiting for my mind to have a breakdown once t...         1
1     My new years resolution : I'm gonna get my ass...         1
2     New year : Somone else Feeling like 2020 will ...         1
3     My story I guess : Hi, Im from Germany and my ...         1
4     Sat in the dark and cried myself going into th...         1
...                                                 ...       ...
8886  Ways to reverse memory loss from depression? :...         2
8887  A Comprehensive Guide To Slowly Getting Better...         2
8888  I don’t think college is right for me : TW: su...         2
8889  Please help: Severe insomnia affecting me in m...         2
8890  With each passing day my depression is getting...         2

[8891 rows x 2 columns]


In [ ]:
df_train.category.unique()

array([1, 0, 2])

In [ ]:
!pip install simpletransformers

     |████████████████████████████████| 249 kB 4.1 MB/s 
     |████████████████████████████████| 43 kB 1.9 MB/s 
     |████████████████████████████████| 325 kB 37.2 MB/s 
     |████████████████████████████████| 10.1 MB 49.4 MB/s 
     |████████████████████████████████| 6.5 MB 38.4 MB/s 
     |████████████████████████████████| 3.8 MB 42.5 MB/s 
     |████████████████████████████████| 1.7 MB 41.6 MB/s 
     |████████████████████████████████| 1.2 MB 40.7 MB/s 
     |████████████████████████████████| 67 kB 5.2 MB/s 
     |████████████████████████████████| 596 kB 42.6 MB/s 
     |████████████████████████████████| 895 kB 40.8 MB/s 
     |████████████████████████████████| 181 kB 51.4 MB/s 
     |████████████████████████████████| 144 kB 49.5 MB/s 
     |████████████████████████████████| 63 kB 1.8 MB/s 
     |████████████████████████████████| 136 kB 42.8 MB/s 
     |████████████████████████████████| 1.1 MB 35.2 MB/s 
     |████████████████████████████████| 212 kB 51.6 MB/s 
     |██████████████

In [ ]:
import pandas as pd
from simpletransformers.classification import ClassificationModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np

np.set_printoptions(threshold=np.inf)

In [ ]:
import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
import re

def preprocess(sentence):
  sentence=str(sentence)
  sentence=sentence.lower()
  cleanr=re.compile('<.*?>')
  cleantext=re.sub(cleanr,'',sentence)
  rem_url=re.sub(r'http\S+','',cleantext)
  rem_num=re.sub('[0-9]+','',rem_url)
  rem_tag=re.sub(r'@\S+','',rem_num)
  tokenizer=RegexpTokenizer(r'\w+')
  tokens=tokenizer.tokenize(rem_tag)
  filtered_words=[w for w in tokens if len(w)>2 if not w in stopwords.words('english')]
  return " ".join(filtered_words)

df_train['text']=df_train['text'].map(lambda s:preprocess(s))
df_train.head(20)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


text  category
0   waiting mind breakdown new year feeling anymor...         1
1   new years resolution gonna get ass therapists ...         1
2   new year somone else feeling like last year ea...         1
3   story guess germany english mostly self learne...         1
4           sat dark cried going new year great start         1
5   probably end mum around anymore say certainty ...         1
6   fuck left abusive relationship moved abusive f...         1
7   new year eve party want cry panic attack witho...         1
8   death father father died beginning december gr...         1
9   empty stuck loop every day order watch youtube...         1
10  officially one wished happy new year already c...         1
11  marriage dog police turning year married polic...         1
12  want die want stop living even make sense god ...         1
13  happy new year fuck bettexaxaxaxaxaxa even hap...         1
14  almost cried family wishing happy new year sta...         1
15  dad got bottle irish cream yesterday downed bu...         1
16  everybody left know making post guess kinda ne...         1
17  know new year eve want kill die think life wor...         1
18  lonely new year know belongs need write little...         1
19  hate life wish never born week since given any...         1

In [ ]:
model=ClassificationModel('roberta','roberta-base',num_labels=3,use_cuda=True,args={
        "reprocess_input_data" : True,
        "use_cached_eval_features":False, 
        "overwrite_output_dir": True, 
        "num_train_epochs": 1}
)

Downloading:   0%|          | 0.00/481 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/478M [00:00<?, ?B/s]

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.decoder.weight', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.out_proj.bias', 'classifi

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

In [ ]:
model.train_model(df_train)

/usr/local/lib/python3.7/dist-packages/simpletransformers/classification/classification_model.py:586: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


  0%|          | 0/8891 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/1112 [00:00<?, ?it/s]

(1112, 0.7597442342223023)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving dev_with_labels.csv to dev_with_labels.csv


In [ ]:
df_eval = pd.read_csv('dev_with_labels.csv')
print(df_eval)

                                                   text  category
0     I enjoyed today, and I still am! Tomorrows dep...         1
1     I sorta tried to kill myself : I had a total b...         1
2     Best suicide method? : I like it quick and eas...         1
3     a story : I remember the time I'd get on my 3D...         1
4     The world only cares about beautiful people : ...         1
...                                                 ...       ...
4491  Aren’t we all just tired? : I’ve been depresse...         2
4492  NEED HELP COPING : I had my life pretty much f...         2
4493  Qutting Zoloft Cold Turkey : I was on 75 mg se...         2
4494  Crying : I’m coming off my antidepressants and...         2
4495  Seeking for advice on how to overcome and deal...         2

[4496 rows x 2 columns]


In [ ]:
result, model_outputs, wrong_predictions = model.eval_model(df_eval)
print(result)

/usr/local/lib/python3.7/dist-packages/simpletransformers/classification/classification_model.py:1427: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


  0%|          | 0/4496 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/562 [00:00<?, ?it/s]

{'mcc': 0.22595289048055303, 'eval_loss': 0.9824561970938143}


In [ ]:
print(wrong_predictions)

[{'guid': 0, 'text_a': "I enjoyed today, and I still am! Tomorrows depression can wait! : Today, I'm warm and cozy :) I even had some tea, to complement my sandwich!\nThis is a crazy time we live in, but it's only the beginning, with the world going to shambles, being alone feels werid.\nBut a stranger came through and saved me,\nOf course it's a debt I'll have to repay, but I'm grateful to have this debt!\nCrazy what a few dollars can do to change someones situation.\nBut these days, it's all about here and now!\nI don't have the ability to relax just because, I'm full, clean, and warm.\nTomorrow it's back to reality! \nThe motel was just to get ourself together! We been out here panicking the past two weeks and the last 3 days exspecially.\nI got blessed this week that's for sure!\nTwo weeks till payday.\nWhat to do, what to do.\nWell I can't just pull another loan, so I gotta make what's left it last. \nPlanet fitness anyone???!! \nOkay actually, gas wise, idk, finding safe places t

In [ ]:
model_outputs

array([[ 2.83789062e+00,  3.03710938e-01, -3.42187500e+00],
       [-9.56054688e-01,  1.49316406e+00, -4.29199219e-01],
       [ 1.72363281e+00, -7.88085938e-01, -1.12988281e+00],
       [ 2.45898438e+00,  6.19140625e-01, -3.30078125e+00],
       [ 1.19335938e+00,  1.56933594e+00, -2.86132812e+00],
       [-5.10253906e-01,  2.23632812e+00, -1.76660156e+00],
       [-3.18115234e-01,  2.34375000e+00, -1.98242188e+00],
       [-6.65527344e-01,  2.52734375e+00, -1.89941406e+00],
       [-1.57226562e+00,  4.79248047e-01,  1.07128906e+00],
       [-3.80859375e-01,  2.57812500e+00, -2.17968750e+00],
       [ 1.35839844e+00,  2.02539062e+00, -3.30468750e+00],
       [ 2.52929688e+00,  1.00097656e+00, -3.52734375e+00],
       [-6.74316406e-01,  2.32031250e+00, -1.69433594e+00],
       [-7.85522461e-02,  2.52148438e+00, -2.36132812e+00],
       [ 3.24804688e+00, -6.36230469e-01, -2.91796875e+00],
       [ 2.27539062e+00,  5.69824219e-01, -2.79882812e+00],
       [ 3.97216797e-01,  2.08593750e+00

In [ ]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt: ignored

In [ ]:
df_test= pd.read_csv('dev_with_labels.csv')
print(df_test)

                                                   text  category
0     I enjoyed today, and I still am! Tomorrows dep...         1
1     I sorta tried to kill myself : I had a total b...         1
2     Best suicide method? : I like it quick and eas...         1
3     a story : I remember the time I'd get on my 3D...         1
4     The world only cares about beautiful people : ...         1
...                                                 ...       ...
4491  Aren’t we all just tired? : I’ve been depresse...         2
4492  NEED HELP COPING : I had my life pretty much f...         2
4493  Qutting Zoloft Cold Turkey : I was on 75 mg se...         2
4494  Crying : I’m coming off my antidepressants and...         2
4495  Seeking for advice on how to overcome and deal...         2

[4496 rows x 2 columns]


In [ ]:
predictions, raw_outputs = model.predict(df_test['text'].tolist())
print(predictions)
print(raw_outputs)


  0%|          | 0/4496 [00:00<?, ?it/s]

  0%|          | 0/562 [00:00<?, ?it/s]

[0 1 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1
 0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1
 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1
 0 1 1 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1
 0 0 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1
 1 1 1 1 1 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0 1 0
 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1
 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1
 1 1 0 0 0 0 1 0 1 1 0 1 

In [ ]:
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action='ignore',category=FutureWarning)
from sklearn.metrics import classification_report
print(classification_report(df_test.category,predictions))

              precision    recall  f1-score   support

           0       0.60      0.44      0.51      1830
           1       0.59      0.80      0.68      2306
           2       0.00      0.00      0.00       360

    accuracy                           0.59      4496
   macro avg       0.40      0.41      0.40      4496
weighted avg       0.55      0.59      0.55      4496



In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df_test.category,predictions))

[[ 802 1028    0]
 [ 450 1856    0]
 [  77  283    0]]


In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2299.998
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4599.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	:

In [ ]:
from psutil import *
virtual_memory()

svmem(total=13622190080, available=9876746240, percent=27.5, used=5174243328, free=283856896, active=4958490624, inactive=7803482112, buffers=205987840, cached=7958102016, shared=5435392, slab=365236224)

In [ ]:
#GPU count and name
!nvidia-smi -L

GPU 0: Tesla K80 (UUID: GPU-56ea2ad3-1b0c-eb1a-c4db-cb5684835ef3)


In [ ]:
#use this command to see GPU activity while doing Deep Learning tasks, for this command 'nvidia-smi' and for above one to work, go to 'Runtime > change runtime type > Hardware Accelerator > GPU'
!nvidia-smi

Tue Apr  5 17:49:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0    59W / 149W |   3583MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!cat /proc/meminfo

MemTotal:       13302920 kB
MemFree:          283748 kB
MemAvailable:    9652840 kB
Buffers:          201384 kB
Cached:          7479132 kB
SwapCached:            0 kB
Active:          4835952 kB
Inactive:        7621196 kB
Active(anon):    3050828 kB
Inactive(anon):     4560 kB
Active(file):    1785124 kB
Inactive(file):  7616636 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               212 kB
Writeback:             0 kB
AnonPages:       4776752 kB
Mapped:          1876996 kB
Shmem:              5308 kB
KReclaimable:     293280 kB
Slab:             357020 kB
SReclaimable:     293280 kB
SUnreclaim:        63740 kB
KernelStack:        5120 kB
PageTables:        37468 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6651460 kB
Committed_AS:    6694452 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       46788 kB
VmallocChunk:          0 kB
Percpu:          

In [ ]:
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action='ignore',category=FutureWarning)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(df_test.label,predictions))

AttributeError: ignored

In [ ]:
df_tes = pd.read_csv('test_data.tsv', sep='\t')
df_tes['category'] = predictions
df_tes.to_csv('scube_run2.csv')

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving roberta.csv to roberta.csv


In [ ]:
df_tes = pd.read_csv('roberta.csv')
df_tes.to_csv('roberta.tsv', sep='\t',index=False)
df_tes.head(20)

Pid  ...     class_label
0    test_pid_1  ...        moderate
1    test_pid_2  ...  not depression
2    test_pid_3  ...        moderate
3    test_pid_4  ...        moderate
4    test_pid_5  ...        moderate
5    test_pid_6  ...        moderate
6    test_pid_7  ...  not depression
7    test_pid_8  ...        moderate
8    test_pid_9  ...          severe
9   test_pid_10  ...          severe
10  test_pid_11  ...        moderate
11  test_pid_12  ...  not depression
12  test_pid_13  ...        moderate
13  test_pid_14  ...  not depression
14  test_pid_15  ...        moderate
15  test_pid_16  ...  not depression
16  test_pid_17  ...        moderate
17  test_pid_18  ...        moderate
18  test_pid_19  ...        moderate
19  test_pid_20  ...  not depression

[20 rows x 3 columns]

In [ ]:
df_tes['category'].value_counts()

KeyError: ignored

In [ ]:
import seaborn as sns
sns.set(rc={'figure.figsize':(8,8)})
#sns.countplot(trainDF_Sheet_1['category'])
sns.countplot(df_test['category'])

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving roberta.csv to roberta.csv


In [ ]:
import pandas as pd

In [ ]:
df_tes = pd.read_csv('roberta.csv')
df_tes.to_csv('scube_run2.tsv', sep='\t',index=False)
df_tes.head(20)

Pid     class_label
0    test_pid_1        moderate
1    test_pid_2  not depression
2    test_pid_3        moderate
3    test_pid_4        moderate
4    test_pid_5        moderate
5    test_pid_6        moderate
6    test_pid_7  not depression
7    test_pid_8        moderate
8    test_pid_9          severe
9   test_pid_10          severe
10  test_pid_11        moderate
11  test_pid_12  not depression
12  test_pid_13        moderate
13  test_pid_14  not depression
14  test_pid_15        moderate
15  test_pid_16  not depression
16  test_pid_17        moderate
17  test_pid_18        moderate
18  test_pid_19        moderate
19  test_pid_20  not depression